---
  - name: Remove CD/DVD from apt source
    become: yes
    become_method: su
    replace:
      path: /etc/apt/sources.list
      regexp: '^(?![#])(.*Official amd64 DVD Binary.*)'
      replace: '#\1'
  - name: Update the apt package index
    become: yes
    become_method: su
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
  - name: Install basic tools
    become: yes
    become_method: su
    apt:
      name: "{{ tools }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
  - name: Add sudo to user groups
    become: yes
    become_method: su
    user:
      name: '{{ user }}'
      groups: sudo
      append: yes
